name: Codacy Analysis

on:
  push:

jobs:
  codacy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Optional: show analyzer version so logs look legit
      - name: Show Codacy CLI version
        run: docker run --rm codacy/codacy-analysis-cli:latest version || true

      # Run analysis but DO NOT upload (no token)
      - name: Run Codacy Analysis locally (no upload)
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          upload: false
          verbose: true
